{% set name = "python-jsonpath" %}
{% set version = "1.3.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_jsonpath-{{ version }}.tar.gz
  sha256: 90d348be9c6f0ee070cb6419d4b2b08fcbb07f5a2a34060b8833bef024099315

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jsonpath
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jg-rp/python-jsonpath
  summary: Another JSONPath implementation for Python.
  dev_url: https://github.com/jg-rp/python-jsonpath
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jacobtomlinson
    - jg-rp
