{% set name = "python-jsonpath" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_jsonpath-{{ version }}.tar.gz
  sha256: 1ab894d11499378c4d7572ba13a5fa9ddcb0402975ece77e3a6a7877d02a9eb5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - jsonpath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jg-rp/python-jsonpath
  summary: Another JSONPath implementation for Python.
  dev_url: https://github.com/jg-rp/python-jsonpath
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jacobtomlinson
    - jg-rp
