{% set name = "python-jsonpath" %}
{% set version = "1.3.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_jsonpath-{{ version }}.tar.gz
  sha256: aa76f07f56f93c63a69b6b5d581dbcf2faf908aefbc5c6bcb7bf98bacfb07548

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jsonpath
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jg-rp/python-jsonpath
  summary: Another JSONPath implementation for Python.
  dev_url: https://github.com/jg-rp/python-jsonpath
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jacobtomlinson
    - jg-rp
