{% set name = "python-jsonpath" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_jsonpath-{{ version }}.tar.gz
  sha256: a29a84ec3ac38e5dcaa62ac2a215de72c4eb60cb1303e10700da980cf7873775

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - jsonpath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jg-rp/python-jsonpath
  summary: Another JSONPath implementation for Python.
  dev_url: https://github.com/jg-rp/python-jsonpath
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jacobtomlinson
    - jg-rp
